# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permify < Formula
  desc "Permify is an open-source authorization service & policy engine based on Google Zanzibar."
  homepage "https://github.com/Permify/permify"
  version "1.1.0"
  license "Apache-2.0"

  depends_on "go" => :build

  on_macos do
    url "https://github.com/Permify/permify/releases/download/v1.1.0/permify_1.1.0_darwin_all.tar.gz", using: CurlDownloadStrategy
    sha256 "1f55bfa78da52938c3ef8d0533fa70df9742529e730db1f27be51b8acc902e08"

    def install
      bin.install "permify"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/permify/releases/download/v1.1.0/permify_1.1.0_linux_amd64.tar.gz", using: CurlDownloadStrategy
        sha256 "6d60befde43358462aa900c65a249473b0a2659b90fc80fe7cc9e8939b55e664"

        def install
          bin.install "permify"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Permify/permify/releases/download/v1.1.0/permify_1.1.0_linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "8d2d766a55d12b355cb70caa77db7d8ba03d05e07b9e83b9c800d4755c4dbdc9"

        def install
          bin.install "permify"
        end
      end
    end
  end

  head "https://github.com/Permify/permify.git", :branch => "master"
end
